APP_REGISTRY = [
    {"symbol":"AI","name":"NeuralBrief AI","description":"Daily and weekly executive intelligence digest for Artificial Intelligence.","category":"Artificial Intelligence","cadence":"Daily / Weekly","status":"active","page":"NeuralBrief_AI","accent":"#A855F7","icon":"brain"},
    {"symbol":"TC","name":"TelecomPulse AI","description":"Strategic telecom intelligence across 5G, RAN, OSS, BSS, cloud and regulation.","category":"Telecom","cadence":"Daily / Weekly","status":"active","page":"TelecomPulse_AI","accent":"#00D4FF","icon":"radio"},
    {"symbol":"CS","name":"CyberShield Brief","description":"Cybersecurity intelligence covering threats, vulnerabilities, ransomware and zero trust.","category":"Cybersecurity","cadence":"Daily / Weekly","status":"active","page":"CyberShield_Brief","accent":"#22C55E","icon":"shield"},
    {"symbol":"CL","name":"CloudPulse AI","description":"Cloud, FinOps, Kubernetes, platform engineering, edge and sovereign cloud digest.","category":"Cloud","cadence":"Weekly","status":"active","page":"CloudPulse_AI","accent":"#38BDF8","icon":"cloud"},
    {"symbol":"DS","name":"DataSphere AI","description":"Data, analytics, lakehouse, governance, MLOps and AI-ready data platforms.","category":"Data & Analytics","cadence":"Weekly","status":"active","page":"DataSphere_AI","accent":"#F59E0B","icon":"database"},
    {"symbol":"DO","name":"DevOps Radar","description":"DevOps, SRE, observability, GitOps, CI/CD and platform engineering briefing.","category":"Engineering","cadence":"Weekly","status":"beta","page":"DevOps_Radar","accent":"#84CC16","icon":"infinity"},
    {"symbol":"EA","name":"EnterpriseApps Pulse","description":"SAP, Salesforce, ServiceNow, Oracle, Workday and enterprise SaaS intelligence.","category":"Enterprise Apps","cadence":"Weekly","status":"beta","page":"EnterpriseApps_Pulse","accent":"#EC4899","icon":"briefcase"},
    {"symbol":"VB","name":"Vendor Battlecard AI","description":"Vendor comparisons, strengths, weaknesses, use cases and client conversation points.","category":"Sales Enablement","cadence":"On Demand","status":"active","page":"Vendor_Battlecard_AI","accent":"#8B5CF6","icon":"scale"},
    {"symbol":"UC","name":"GenAI Use Case Studio","description":"Generate GenAI use cases by industry, function, maturity and business value.","category":"GenAI Advisory","cadence":"On Demand","status":"active","page":"GenAI_Use_Case_Studio","accent":"#06B6D4","icon":"lightbulb"},
    {"symbol":"AR","name":"Architecture Library","description":"Reference architectures for RAG, agents, cloud, data, security and platform patterns.","category":"Architecture","cadence":"On Demand","status":"active","page":"Architecture_Library","accent":"#3B82F6","icon":"box"},
    {"symbol":"RG","name":"RegulationWatch AI","description":"AI, data, cyber, cloud sovereignty and digital regulation tracker.","category":"Governance","cadence":"Weekly","status":"disabled","page":"RegulationWatch_AI","accent":"#64748B","icon":"gavel"},
]
