APP_REGISTRY = [
    {"symbol":"AI","name":"NeuralBrief AI","description":"Daily and weekly executive intelligence digest for Artificial Intelligence.","category":"Artificial Intelligence","cadence":"Daily / Weekly","status":"active","page":"pages/NeuralBrief_AI.py","accent":"#A855F7"},
    {"symbol":"TC","name":"TelecomPulse AI","description":"Strategic telecom intelligence across 5G, RAN, OSS, BSS, cloud and regulation.","category":"Telecom","cadence":"Daily / Weekly","status":"active","page":"pages/TelecomPulse_AI.py","accent":"#00D4FF"},
    {"symbol":"CS","name":"CyberShield Brief","description":"Cybersecurity intelligence covering threats, vulnerabilities, ransomware and zero trust.","category":"Cybersecurity","cadence":"Daily / Weekly","status":"active","page":"pages/CyberShield_Brief.py","accent":"#22C55E"},
    {"symbol":"CL","name":"CloudPulse AI","description":"Cloud, FinOps, Kubernetes, platform engineering, edge and sovereign cloud digest.","category":"Cloud","cadence":"Weekly","status":"active","page":"pages/CloudPulse_AI.py","accent":"#38BDF8"},
    {"symbol":"DS","name":"DataSphere AI","description":"Data, analytics, lakehouse, governance, MLOps and AI-ready data platforms.","category":"Data & Analytics","cadence":"Weekly","status":"active","page":"pages/DataSphere_AI.py","accent":"#F59E0B"},
    {"symbol":"DO","name":"DevOps Radar","description":"DevOps, SRE, observability, GitOps, CI/CD and platform engineering briefing.","category":"Engineering","cadence":"Weekly","status":"beta","page":"pages/DevOps_Radar.py","accent":"#4ADE80"},
    {"symbol":"EA","name":"EnterpriseApps Pulse","description":"SAP, Salesforce, ServiceNow, Oracle, Workday and enterprise SaaS intelligence.","category":"Enterprise Apps","cadence":"Weekly","status":"beta","page":"pages/EnterpriseApps_Pulse.py","accent":"#EC4899"},
    {"symbol":"VB","name":"Vendor Battlecard AI","description":"Vendor comparisons, strengths, weaknesses, use cases and client conversation points.","category":"Sales Enablement","cadence":"On Demand","status":"active","page":"pages/Vendor_Battlecard_AI.py","accent":"#8B5CF6"},
    {"symbol":"UC","name":"GenAI Use Case Studio","description":"Generate GenAI use cases by industry, function, maturity and business value.","category":"GenAI Advisory","cadence":"On Demand","status":"active","page":"pages/GenAI_Use_Case_Studio.py","accent":"#06B6D4"},
    {"symbol":"TR","name":"TechRadar Builder","description":"Build technology radars with Adopt, Trial, Assess and Hold recommendations.","category":"Strategy","cadence":"On Demand","status":"active","page":"pages/TechRadar_Builder.py","accent":"#C084FC"},
    {"symbol":"AR","name":"Architecture Library","description":"Reference architectures for RAG, agents, cloud, data, platform engineering and zero trust.","category":"Architecture","cadence":"On Demand","status":"active","page":"pages/Architecture_Library.py","accent":"#60A5FA"},
    {"symbol":"RG","name":"RegulationWatch AI","description":"AI, data, cyber, cloud sovereignty and digital regulation tracker.","category":"Governance","cadence":"Weekly","status":"disabled","page":"pages/RegulationWatch_AI.py","accent":"#94A3B8"},
]
